export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const SUCCESS_LOGIN = 'SUCCESS_LOGIN';
export const SUCCESS_GET_USER = 'SUCCESS_GET_USER';
export const GET_CHAT_MESSAGES = 'GET_CHAT_MESSAGES';
export const SAVE_CHAT_MESSAGE = 'SAVE_CHAT_MESSAGE';
