export const GET_ALL_ACCOMMODATIONS_START = 'GET_ALL_ACCOMMODATIONS_START';
export const GET_ALL_ACCOMMODATIONS_SUCCESS = 'GET_ALL_ACCOMMODATIONS_SUCCESS';
export const GET_ALL_ACCOMMODATIONS_ERROR = 'GET_ALL_ACCOMMODATIONS_ERROR';

export const GET_SINGLE_ACCOMMODATION_START = 'GET_SINGLE_ACCOMMODATION_START';
export const GET_SINGLE_ACCOMMODATION_SUCCESS = 'GET_SINGLE_ACCOMMODATION_SUCCESS';
export const GET_SINGLE_ACCOMMODATION_ERROR = 'GET_SINGLE_ACCOMMODATION_ERROR';

export const FILTER_ACCOMMODATIONS = 'FILTER_ACCOMMODATIONS';
