export const PREFIX = 'MANAGER';
export const GET_TRIP_REQUEST_START = 'GET_TRIP_REQUEST_START';
export const GET_TRIP_REQUEST_SUCCESS = 'GET_TRIP_REQUEST_SUCCESS';
export const GET_TRIP_REQUEST_ERROR = 'GET_TRIP_REQUEST_ERROR';

// export const HANDLE_PAGE_CHANGE = 'HANDLE_PAGE_CHANGE';
// export const HANDLE_ROWS_PER_PAGE_CHANGE = 'HANDLE_ROWS_PER_PAGE_CHANGE';
