export const PREFIX = 'MANAGER';
export const GET_TRIP_REQUEST_START = 'GET_TRIP_REQUEST_START';
export const GET_TRIP_REQUEST_SUCCESS = 'GET_TRIP_REQUEST_SUCCESS';
export const GET_TRIP_REQUEST_ERROR = 'GET_TRIP_REQUEST_ERROR';

// export const HANDLE_PAGE_CHANGE = 'HANDLE_PAGE_CHANGE';
// export const HANDLE_ROWS_PER_PAGE_CHANGE = 'HANDLE_ROWS_PER_PAGE_CHANGE';

// Status
export const APPROVE_REJECT_SUCCESS = 'APPROVE_REJECT_SUCCESS';
export const APPROVE_REJECT_ERROR = 'APPROVE_REJECT_ERROR';
// statistics
export const TRIPS_STATS_BEGIN = 'TRIPS_STATS_BEGIN';
export const TRIPS_STATS_SUCCESS = 'TRIPS_STATS_SUCCESS';
export const TRIPS_STATS_ERROR = 'TRIPS_STATS_ERROR';
// most visited
export const MOST_VISITED = "MOST_VISITED";