export const CREATE_REQUEST_START = 'CREATE_REQUEST_START';
export const CREATE_REQUEST_SUCCESS = 'CREATE_REQUEST_SUCCESS';
export const CREATE_REQUEST_ERROR = 'CREATE_REQUEST_ERROR';

export const GET_REQUEST_START = 'GET_REQUEST_START';
export const GET_REQUEST_SUCCESS = 'GET_REQUEST_SUCCESS';
export const GET_REQUEST_ERROR = 'GET_REQUEST_ERROR';

export const EDIT_REQUEST_START = 'EDIT_REQUEST_START';
export const EDIT_REQUEST_SUCCESS = 'EDIT_REQUEST_SUCCESS';
export const EDIT_REQUEST_ERROR = 'EDIT_REQUEST_ERROR';

export const GET_ACCOMMODATIONS_START = 'GET_ACCOMMODATIONS_START';
export const GET_ACCOMMODATIONS_SUCCESS = 'GET_ACCOMMODATIONS_SUCCESS';
export const GET_ACCOMMODATIONS_ERROR = 'GET_ACCOMMODATIONS_ERROR';