export const ACCOMMODATION_START = 'ACCOMMODATION_START';
export const CREATE_ACCOMMODATION_START = 'CREATE_ACCOMMODATION_START';
export const CREATE_ACCOMMODATION_SUCCESS = 'CREATE_ACCOMMODATION_SUCCESS';
export const CREATE_ACCOMMODATION_ERROR = 'CREATE_ACCOMMODATION_ERROR';

export const GET_ACCOMMODATION_SUCCESS = 'GET_ACCOMMODATION_SUCCESS';
export const GET_ACCOMMODATION_ERROR = 'GET_ACCOMMODATION_ERROR';

export const UPDATE_ON_CREATE_ACCOMMODATION = 'UPDATE_ON_CREATE_ACCOMMODATION';

// export const ACCOMMODATION_START = 'CREATE_ACCOMMODATION_START';
export const CREATE_ROOM_START = 'CREATE_ROOM_START';
export const CREATE_ROOM_SUCCESS = 'CREATE_ROOM_SUCCESS';
export const CREATE_ROOM_ERROR = 'CREATE_ROOM_ERROR';

export const GET_ROOM_SUCCESS = 'GET_ROOM_SUCCESS';
export const GET_ROOM_ERROR = 'GET_ROOM_ERROR';
